spring.application.name=qruta-trazabilidad

# PostgreSQL levantado con docker compose (ver docker-compose.yml)
spring.datasource.url=jdbc:postgresql://localhost:5433/qruta_db
spring.datasource.username=qruta
spring.datasource.password=qruta

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
